# Guide (user-friendly):
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

# Specification (technical, formal):
# https://packaging.python.org/en/latest/specifications/pyproject-toml/


# Choosing a build backend:
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend
[build-system]
requires = ["setuptools>=38.3.0", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "liger_iris_sim/_version.py"
version_scheme = "post-release"

[project]
name = "liger_iris_sim"
dynamic = ["version"]
description = "Extra data resources for the Liger IRIS Data Reduction Pipeline (DRP; liger_iris_pipeline) and Data Simulator (liger_iris_sim)."
readme = "README.md"
requires-python = ">=3.12"

license = {file = "LICENSE.md"}

authors = [
  {name = "Bryson Cale", email = "brcale@ucsd.edu" },
]

maintainers = [
  {name = "Bryson Cale", email = "brcale@ucsd.edu" },
]

classifiers = [
  "Development Status :: 1 - Planning",
  "Topic :: Scientific/Engineering :: Astronomy",
  # "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "numpy>=2",
  "astropy>=7.0",
  "scipy",
  # "matplotlib",
  "liger_iris_drp_resources @ git+https://github.com/astrobc1/Liger_IRIS_DRP_Resources"
]

[project.optional-dependencies]
docs = ["sphinx==8.1.3", "nbsphinx", "pandoc", "sphinx-multiversion", "sphinxawesome-theme", "matplotlib"]
test = ["pytest", "pytest-cov", "pytest-astropy", "nbval"]
dev = ["nbstripout"]

[project.urls]
"Documentation" = "https://oirlab.github.io/liger_iris_sim"
"Source" = "https://github.com/oirlab/liger_iris_sim"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--rootdir=."